-- 审计保留策略、证据保全和清理批次证据。领域审计仍保存在各自权威表中。

CREATE TABLE `sys_audit_retention_policy` (
    `policy_id` VARCHAR(32) NOT NULL,
    `data_category` VARCHAR(64) NOT NULL,
    `source_module` VARCHAR(50) NOT NULL,
    `retention_period` VARCHAR(20) NOT NULL COMMENT 'ISO-8601日历期限，例如P6M或P1Y',
    `cleanup_enabled` TINYINT(1) NOT NULL,
    `effective_at` DATETIME(3) NOT NULL,
    `policy_version` INT NOT NULL,
    `lifecycle_status` VARCHAR(20) NOT NULL COMMENT 'CURRENT或SUPERSEDED',
    `change_reason` VARCHAR(500) NOT NULL,
    `request_id` VARCHAR(32) NOT NULL,
    `approved_by` BIGINT NOT NULL,
    `approved_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`policy_id`),
    UNIQUE KEY `uk_audit_retention_source_version` (`source_module`,`policy_version`),
    KEY `idx_audit_retention_current` (`source_module`,`lifecycle_status`,`effective_at`),
    KEY `idx_audit_retention_request` (`request_id`),
    CONSTRAINT `chk_audit_retention_lifecycle` CHECK (`lifecycle_status` IN ('CURRENT','SUPERSEDED')),
    CONSTRAINT `chk_audit_retention_version` CHECK (`policy_version` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审核后不可原地改写的审计保留策略版本';

CREATE TABLE `sys_audit_evidence_hold` (
    `hold_id` VARCHAR(32) NOT NULL,
    `source_module` VARCHAR(50) NULL,
    `audit_id` VARCHAR(32) NULL,
    `building_id` VARCHAR(32) NULL,
    `action_type` VARCHAR(64) NULL,
    `object_type` VARCHAR(64) NULL,
    `object_id` VARCHAR(128) NULL,
    `from_time` DATETIME(3) NULL,
    `to_time` DATETIME(3) NULL,
    `investigation_id` VARCHAR(100) NULL,
    `reason` VARCHAR(500) NOT NULL,
    `legal_basis` VARCHAR(500) NOT NULL,
    `starts_at` DATETIME(3) NOT NULL,
    `review_at` DATETIME(3) NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `created_by` BIGINT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `released_by` BIGINT NULL,
    `released_at` DATETIME(3) NULL,
    `release_request_id` VARCHAR(32) NULL,
    `release_reason` VARCHAR(500) NULL,
    PRIMARY KEY (`hold_id`),
    KEY `idx_audit_hold_active_source` (`status`,`source_module`,`review_at`,`hold_id`),
    KEY `idx_audit_hold_audit` (`status`,`source_module`,`audit_id`),
    KEY `idx_audit_hold_building_time` (`status`,`building_id`,`from_time`,`to_time`),
    KEY `idx_audit_hold_object` (`status`,`object_type`,`object_id`),
    KEY `idx_audit_hold_investigation` (`investigation_id`,`status`),
    CONSTRAINT `chk_audit_hold_status` CHECK (`status` IN ('ACTIVE','RELEASED')),
    CONSTRAINT `chk_audit_hold_time` CHECK (`to_time` IS NULL OR `from_time` IS NULL OR `to_time` > `from_time`),
    CONSTRAINT `chk_audit_hold_review` CHECK (`review_at` > `starts_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='阻止审计证据到期清理的保全范围';

CREATE TABLE `sys_audit_cleanup_run` (
    `run_id` VARCHAR(32) NOT NULL,
    `trigger_type` VARCHAR(20) NOT NULL COMMENT 'AUTOMATIC或EXCEPTION',
    `policy_id` VARCHAR(32) NULL,
    `policy_version` INT NULL,
    `data_category` VARCHAR(64) NOT NULL,
    `source_module` VARCHAR(50) NOT NULL,
    `building_id` VARCHAR(32) NULL,
    `cutoff_time` DATETIME(3) NULL,
    `scope_json` JSON NULL COMMENT '审核冻结的删除范围，不保存被删除记录内容',
    `candidate_count` BIGINT NOT NULL DEFAULT 0,
    `deleted_count` BIGINT NOT NULL DEFAULT 0,
    `held_count` BIGINT NOT NULL DEFAULT 0,
    `protected_count` BIGINT NOT NULL DEFAULT 0,
    `earliest_operation_time` DATETIME(3) NULL,
    `latest_operation_time` DATETIME(3) NULL,
    `status` VARCHAR(20) NOT NULL,
    `error_code` VARCHAR(64) NULL,
    `system_actor` VARCHAR(64) NOT NULL,
    `triggered_by` BIGINT NULL,
    `trigger_request_id` VARCHAR(32) NULL,
    `trace_id` VARCHAR(64) NOT NULL,
    `manifest_sha256` CHAR(64) NULL,
    `started_at` DATETIME(3) NOT NULL,
    `completed_at` DATETIME(3) NULL,
    PRIMARY KEY (`run_id`),
    KEY `idx_audit_cleanup_status` (`status`,`started_at`,`run_id`),
    KEY `idx_audit_cleanup_source_time` (`source_module`,`started_at`,`run_id`),
    KEY `idx_audit_cleanup_policy` (`policy_id`,`policy_version`,`started_at`),
    KEY `idx_audit_cleanup_request` (`trigger_request_id`),
    KEY `idx_audit_cleanup_trace` (`trace_id`),
    CONSTRAINT `chk_audit_cleanup_trigger` CHECK (`trigger_type` IN ('AUTOMATIC','EXCEPTION')),
    CONSTRAINT `chk_audit_cleanup_status` CHECK (`status` IN ('PENDING','RUNNING','PARTIAL','SUCCEEDED','FAILED')),
    CONSTRAINT `chk_audit_cleanup_counts` CHECK (`candidate_count` >= 0 AND `deleted_count` >= 0
        AND `held_count` >= 0 AND `protected_count` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='长期保留的审计清理范围、数量和校验证据';
