package com.platform.audit;

/** 固定后台职责目录。职责不是正式业务角色，也不写入 JWT。 */
public enum BackendDuty {
    BACKOFFICE_CHANGE_SUBMITTER,
    BACKOFFICE_CHANGE_REVIEWER,
    AUDIT_EVIDENCE_VIEWER,
    AUDIT_EVIDENCE_EXPORTER,
    AUDIT_RETENTION_MANAGER,
    AUDIT_EVIDENCE_HOLD_MANAGER,
    ENERGY_CATALOG_MAINTAIN,
    ENERGY_CATALOG_REVIEW,
    ENERGY_RULE_MAINTAIN,
    ENERGY_RULE_REVIEW,
    ENERGY_CALCULATION_RUN,
    ENERGY_LOCK_SUBMIT,
    ENERGY_LOCK_APPROVE,
    ENERGY_EXCEPTION_APPROVE,
    ENERGY_RECALC_SUBMIT,
    ENERGY_RECALC_APPROVE,
    CARBON_RULE_MAINTAIN,
    CARBON_RULE_REVIEW,
    CARBON_RULE_ACTIVATE,
    CARBON_CALCULATION_RUN,
    CARBON_RECALCULATION_TRIGGER,
    CARBON_RECALCULATION_APPROVE
}
