DROP TABLE IF EXISTS biz_daikin_state_event;
DROP TABLE IF EXISTS biz_daikin_current_state;
DROP TABLE IF EXISTS biz_daikin_exception_instance;
DROP TABLE IF EXISTS biz_daikin_source_result;
DROP TABLE IF EXISTS biz_daikin_monitoring_target;

CREATE TABLE biz_daikin_monitoring_target (
  identity_id VARCHAR(32) PRIMARY KEY, source_id VARCHAR(200) NOT NULL, pending_id VARCHAR(32),
  equipment_id VARCHAR(32) NOT NULL, building_id VARCHAR(32) NOT NULL, space_id VARCHAR(32),
  system_group_id VARCHAR(32), mapping_version INT NOT NULL, active TINYINT NOT NULL,
  first_planned_at_ms BIGINT NOT NULL, last_valid_at_ms BIGINT, last_round_id BIGINT
);
CREATE TABLE biz_daikin_current_state (
  identity_id VARCHAR(32) NOT NULL, field_name VARCHAR(100) NOT NULL, source_id VARCHAR(200) NOT NULL,
  pending_id VARCHAR(32), equipment_id VARCHAR(32) NOT NULL, building_id VARCHAR(32) NOT NULL,
  space_id VARCHAR(32), system_group_id VARCHAR(32), mapping_version INT NOT NULL,
  raw_json VARCHAR(1024), normalized_value VARCHAR(1024), field_status VARCHAR(16) NOT NULL,
  last_valid_at_ms BIGINT, last_attempt_raw_json VARCHAR(1024), last_attempt_at_ms BIGINT NOT NULL,
  last_attempt_building_id VARCHAR(32) NOT NULL, last_attempt_space_id VARCHAR(32),
  last_attempt_system_group_id VARCHAR(32), last_attempt_mapping_version INT NOT NULL,
  last_round_id BIGINT NOT NULL,
  PRIMARY KEY(identity_id,field_name)
);
CREATE TABLE biz_daikin_state_event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, identity_id VARCHAR(32) NOT NULL,
  field_name VARCHAR(100) NOT NULL, round_id BIGINT NOT NULL, source_id VARCHAR(200) NOT NULL,
  pending_id VARCHAR(32), equipment_id VARCHAR(32) NOT NULL, building_id VARCHAR(32) NOT NULL,
  space_id VARCHAR(32), system_group_id VARCHAR(32), mapping_version INT NOT NULL,
  before_raw_json VARCHAR(1024), before_normalized_value VARCHAR(1024),
  after_raw_json VARCHAR(1024), after_normalized_value VARCHAR(1024) NOT NULL,
  previous_observed_at_ms BIGINT NOT NULL, observed_at_ms BIGINT NOT NULL, after_gap TINYINT NOT NULL,
  UNIQUE(identity_id,field_name,round_id)
);
CREATE TABLE biz_daikin_exception_instance (
  exception_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, active_key VARCHAR(512),
  exception_type VARCHAR(40) NOT NULL, scope_type VARCHAR(16) NOT NULL, source_id VARCHAR(200) NOT NULL,
  identity_id VARCHAR(32), field_name VARCHAR(100), pending_id VARCHAR(32), equipment_id VARCHAR(32),
  building_id VARCHAR(32), space_id VARCHAR(32), system_group_id VARCHAR(32), mapping_version INT,
  first_detected_at_ms BIGINT NOT NULL, last_detected_at_ms BIGINT NOT NULL,
  recovered_at_ms BIGINT, last_round_id BIGINT, UNIQUE(active_key)
);
CREATE TABLE biz_daikin_source_result (
  source_id VARCHAR(200) PRIMARY KEY, last_result_round_id BIGINT, consecutive_failure_rounds INT NOT NULL
);
